// sponsor/sponsors.js
window.GM_SPONSORS = [
  { name: "Trattoria (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🍝", bg: "#fde68a", fg: "#111827" },
  { name: "Bar Genovese (SPAZIO DISPONIBILE)",    url: "https://example.com", ico: "☕", bg: "#93c5fd", fg: "#111827" },
  { name: "Disco Sì (SPAZIO DISPONIBILE)",        url: "https://example.com", ico: "⭐", bg: "#a7f3d0", fg: "#111827" },
  { name: "SDAC - Scuola D'Arte Cinematografica",            url: "https://sdac.it",     ico: "🎬", bg: "#111827", fg: "#ffffff" },
  { name: "Acquario",        url: "https://example.com", ico: "☕", bg: "#93c5fd", fg: "#111827" },
  { name: "Vini pregiati (SPAZIO DISPONIBILE)",   url: "https://example.com", ico: "🍷", bg: "#fde68a", fg: "#111827" },
  { name: "Auto usate (SPAZIO DISPONIBILE)",      url: "https://example.com", ico: "🚗", bg: "#93c5fd", fg: "#111827" },
  { name: "SDAC - Scuola D'Arte Cinematografica",            url: "https://sdac.it",     ico: "🎬", bg: "#111827", fg: "#ffffff" },
  { name: "Biglietti Genoa - Juventus domenica, 25 gennaio ore 18:30",    url: "https://example.com", ico: "⚽", bg: "#93c5fd", fg: "#111827" },
  
{ name: "Pizzeria (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🍕", bg: "#fde68a", fg: "#111827" },
{ name: "Pub / Birreria (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🍺", bg: "#fde68a", fg: "#111827" },
{ name: "Enoteca / Wine bar (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🍷", bg: "#93c5fd", fg: "#111827" },
{ name: "Pasticceria / Panificio (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🥐", bg: "#fde68a", fg: "#111827" },
{ name: "Gelateria (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🍦", bg: "#93c5fd", fg: "#111827" },

{ name: "Discoteca / Club (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🎶", bg: "#fde68a", fg: "#111827" },
{ name: "Teatro: GLI SBANDATI - con Alicero Spinaci e Tullio Certo, regia di Luca.", url: "https://example.com", ico: "🎭", bg: "#93c5fd", fg: "#111827" },
{ name: "Cinema: A VOLTE C'ERO - con Pippo Giuro e Giulia Alcallo, regia di Pippo Giuro.", url: "https://example.com", ico: "🎬", bg: "#fde68a", fg: "#111827" },
{ name: "Live music / Locali musicali (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🎸", bg: "#93c5fd", fg: "#111827" },
{ name: "Sala giochi / Escape room (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🎮", bg: "#fde68a", fg: "#111827" },
{ name: "Galleria / Arte (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🎨", bg: "#93c5fd", fg: "#111827" },
{ name: "Acquario", url: "https://example.com", ico: "🐠", bg: "#fde68a", fg: "#111827" },
{ name: "Noleggio auto (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🚗", bg: "#93c5fd", fg: "#111827" },
{ name: "Sauna e benessere (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🧖", bg: "#fde68a", fg: "#111827" },
{ name: "Campi da calcio (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "⚽", bg: "#93c5fd", fg: "#111827" },
{ name: "SDAC - Scuola D'Arte Cinematografica",            url: "https://sdac.it",     ico: "🎬", bg: "#111827", fg: "#ffffff" },

{ name: "Palestra (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🏋️", bg: "#fde68a", fg: "#111827" },
{ name: "Yoga / Pilates (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🧘", bg: "#93c5fd", fg: "#111827" },
{ name: "Centro benessere / Spa (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "💆", bg: "#fde68a", fg: "#111827" },
{ name: "Studio medico / Poliambulatorio (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🩺", bg: "#93c5fd", fg: "#111827" },
{ name: "Farmacia BEN TI STA - visite in promo.", url: "https://example.com", ico: "💊", bg: "#fde68a", fg: "#111827" },

{ name: "Hotel / B&B (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🏨", bg: "#93c5fd", fg: "#111827" },
{ name: "Agenzia viaggi / Tour (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🧳", bg: "#fde68a", fg: "#111827" },
{ name: "Escursioni mare / Porto (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🛥️", bg: "#93c5fd", fg: "#111827" },
{ name: "Trasporti / Taxi (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🚖", bg: "#fde68a", fg: "#111827" },
{ name: "Guide turistiche (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🗺️", bg: "#93c5fd", fg: "#111827" },
{ name: "SDAC - Scuola D'Arte Cinematografica",            url: "https://sdac.it",     ico: "🎬", bg: "#111827", fg: "#ffffff" },

{ name: "Banca (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🏦", bg: "#fde68a", fg: "#111827" },
{ name: "Assicurazione (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🛡️", bg: "#93c5fd", fg: "#111827" },
{ name: "IMMOBILIARE.GE - La casa come non l'hai mai trovata.", url: "https://example.com", ico: "🏢", bg: "#fde68a", fg: "#111827" },
{ name: "Università / Scuola (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🎓", bg: "#93c5fd", fg: "#111827" },
{ name: "Fondazione / Ente culturale (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🏛️", bg: "#fde68a", fg: "#111827" },
{ name: "Museo", url: "https://example.com", ico: "🏛️", bg: "#93c5fd", fg: "#111827" },

{ name: "Negozio (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🛍️", bg: "#fde68a", fg: "#111827" },
{ name: "Servizi digitali / IT (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🧑‍💻", bg: "#93c5fd", fg: "#111827" },
{ name: "Stampa / Grafica (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🖨️", bg: "#fde68a", fg: "#111827" },
{ name: "Artigiani / Manutenzione (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🔧", bg: "#93c5fd", fg: "#111827" },
{ name: "Barche e Yacht (SPAZIO DISPONIBILE)", url: "https://example.com", ico: "🛥️", bg: "#fde68a", fg: "#111827" }];
